CREATE TABLE SAIDAPRODUTOSDETALHES
(
SAIDAPRODUTO_ID INT NOT NULL REFERENCES SAIDAPRODUTOS(ID),
PRODUTO_ID INT NOT NULL REFERENCES PRODUTOS(ID),
CLIENTE_ID int FOREIGN KEY REFERENCES CLIENTES(ID) NOT NULL,
QUANTIDADE INT NOT NULL,
VALOR_UNITARIO FLOAT NOT NULL,
PRIMARY KEY (SAIDAPRODUTO_ID, PRODUTO_ID)
)