SELECT * FROM CLIENTES 
            WHERE CLIENTES.ID NOT IN (SELECT CHECKINS.CLIENTE_ID WHERE CHECKINS.PENDENTE_CHECKOUT NOT LIKE 1)

			SELECT CHECKINS.CLIENTE_ID WHERE CHECKINS.PENDENTE_CHECKOUT NOT LIKE 1

			select * from CHECKINS WHERE CHECKINS.PENDENTE_CHECKOUT NOT LIKE 1