SELECT SP.ID 'IDLOTE',
                SP.DATA_SAIDA 'DATA',
                P.NOME 'PRODUTO',
                SP.VALOR_TOTAL 'VALOR_LOTE',
                CL.NOME 'NOME_CLIENTE', 
                SD.QUANTIDADE 'QUANTIDADE' ,
                SD.VALOR_UNITARIO 'VALOR_UNITARIO'
                FROM SAIDAPRODUTOSDETALHES SD
                INNER JOIN SAIDAPRODUTOS SP ON SD.SAIDAPRODUTO_ID=SP.ID 
                INNER JOIN PRODUTOS P ON SD.PRODUTO_ID= P.ID 
                INNER JOIN CHECKINS CH ON SP.checkin_id= CH.ID
                INNER JOIN CLIENTES CL ON CL.ID= CH.CLIENTE_ID